### ISSUE TITLE
Windows wallet neo-gui-1.1.0.exe cannot be used

### ISSUE THREAD

**Issue by helsins** [neo-ngd/Neo3-GUI#103]
I installed the latest version of neo-gui-1.1.0.exe and opened neo-gui.exe. However, from 11am until now (2:49pm), the interface was always showing "- / - Connecting ", and of course, there was a rotating circle behind it.
I couldn't create a wallet, I couldn't import a wallet (I chose a file location, entered a password, and hit confirm, but nothing happened).

**Comment by helsins** [comment]
![neo issue](https://user-images.githubusercontent.com/34838187/115193665-0aab7900-a11f-11eb-9bd5-3e3f4889f05b.jpg)

**Comment by Ashuaidehao** [comment]
Could you restart your neo3-gui? If not work, please restart you compute first.

**Comment by helsins** [comment]
thank you Ashuaidehao！
I have restarted the Neo GUI several times and the computer has been rebooted for over an hour and the problem is still there...

**Comment by Ashuaidehao** [comment]
Please check which program is using your 8081 port. Follow the steps:
1. Open command line window
2. Run command:   
`netstat -ano |findstr 8081`
3. Get the process **pid** from step2, then run command:  tasklist|findstr **pid**

**Comment by Ashuaidehao** [comment]
In addition, please download the lastest version(v1.2.3) for test. The old version is not compatible with current neo3 testnet.

**Comment by helsins** [comment]
Where can i find the lastest version？
I have checked that port 8081 is used by neo-gui itself.
![neo](https://user-images.githubusercontent.com/34838187/115220248-e52c6880-a13a-11eb-8425-642ca3b34324.jpg)

**Comment by Ashuaidehao** [comment]
下载地址: [https://github.com/neo-ngd/Neo3-GUI/releases/tag/v1.2.3](https://github.com/neo-ngd/Neo3-GUI/releases/tag/v1.2.3) .
还需要确定下你的电脑安装 [.net 5](https://dotnet.microsoft.com/download) 了吗？

**Comment by helsins** [comment]
很高兴可以中文交流！
我下载了.net5的SDK： windowsdesktop-runtime-5.0.5-win-x64.exe，
也下载了Neo-GUI.Setup.1.2.3 .exe，
都安装完之后重启电脑，然后运行Neo-GUI，依然不能打开钱包文件，不能创建钱包，依然是一直处于“- / - 正在连接”...

**Comment by helsins** [comment]
![Uploading neo1.jpg…]()

**Comment by Ashuaidehao** [comment]
右键用管理员权限可以启动吗？

**Comment by helsins** [comment]
我昨天在电脑上找到2018年的Neo-GUI安装文件了，2.9.6832.1390版本，打开后直接就有5个连接，我的钱包文件也打开了，遗憾的是里面只有9个NEO，当年多存点好了：D
我还是直接发到交易所里放着吧，钱包再升级怕打不开了
