### ISSUE TITLE
Error 20026 - Engine Faulted

### ISSUE THREAD

**Issue by MatthewShelby** [neo-ngd/Neo3-GUI#63]
I am trying to deploy a smart contract using **neo3 GUI**.
I have built my project and both .nef and .manifest.json Files have been generated correctly.

I Browsed them in the Deploy DIalog input fields.
(neo3 Gui Opened in Run As Administrator mode)
I faced this error after I clicked on the test deploy.

![1399-03-15 14_16_52-Neo GUI](https://user-images.githubusercontent.com/47936625/83742997-596b3400-a66f-11ea-918d-1856b6cf3d73.png)

I test rebuilding the project and didn't work.
I found nothing about the error code.
Does anybody know anything about this?
Is there any reference for error codes?

**Comment by wanglongfei88** [comment]
Did you wait until GUI sync the block to the highest as Neo3-preview2 ？

**Comment by Ashuaidehao** [comment]
Make sure you have enough gas to deploy contract，you can apply some gas from https://neowish.ngd.network/neo3/ . 
If it still not work, could you upload your "nef" and "manifest.json" files here? We will help to investigate it.

**Comment by wanglongfei88** [comment]
@MatthewShelby Is this still a problem for you ?

**Comment by wanglongfei88** [comment]
@MatthewShelby We are closing this issue since there is no feedbacks after longtime.
