### ISSUE TITLE
It takes a lot of time to download all the weddings.

### ISSUE THREAD

**Issue by ethdig** [neo-ngd/Neo3-GUI#69]
It takes a lot of time to download all the weddings.
sorry a complete nonsense.

I have been trying to test since yesterday.
and very little information about contracts.
three sample contracts are given : 
we need more examples.

**Comment by wanglongfei88** [comment]
Download weddings ? I am lost.

what's kind of examples do you need? let's know

**Comment by ethdig** [comment]
wedding download takes too long.

a contract distributes the token.
and after a while (the contract owner decides) X distributes NEO to the token holders:

Sample :
total X token accounts:
Distribute: 300 Neo (x tokens get% share)

**Comment by ethdig** [comment]
and no contract compilation and contract submission promotional video
