### ISSUE TITLE
visual studio compilation suffering

### ISSUE THREAD

**Issue by ethdig** [neo-ngd/Neo3-GUI#70]
visual studio , the compilation was a total agony (Of course I couldn't compile) 
                 https://docs.neo.org/v3/docs/en-us/sc/gettingstarted/develop.html
Load this, Upload this, Do this.
suffering.

"simply beautiful" are far from simplicity. 
you should know that not everyone knows good programming. Design simply.

my suggestion: 
make an ide with java and put all Neo libraries inside.
The user just paste the code and compile the code.

sorry this way is very tiring, long troublesome.

footnote: Ethereum currently fewer documents are created and code compilation problem.
Please be simple.

**Comment by wanglongfei88** [comment]
@ethdig thank you very much for your advice
