### ISSUE TITLE
Result when invoking the smart contract entry point

### ISSUE THREAD

**Issue by meevee98** [neo-ngd/Neo3-GUI#71]
I'm trying to invoke a smart contract using its entry point.
I've built a simple smart contract, that only returns the arguments that it receives:
```python
def Main(operation: str, args: list) -> Any:
    return args
```
But when I invoke it using the neo-gui I get the following result:
```
{
   "gasConsumed":"0.0101549",
   "vmState":"HALT",
   "resultStack":[
      {
         "typeCode":16,
         "type":"Array",
         "value":[
            {
               "typeCode":5,
               "type":"ByteArray",
               "value":"74657374",
               "valueString":"test"
            },
            {
               "typeCode":16,
               "type":"Array",
               "value":[
                  {
                     "typeCode":2,
                     "type":"Integer",
                     "value":"10"
                  }
               ]
            }
         ]
      }
   ]
}
```
![image](https://user-images.githubusercontent.com/19419485/86630002-9c883200-bfa2-11ea-8c05-47add631cb7e.png)

I get that when I'm invoking the smart contract like this, neo-gui is actually calling the entry point with ``operation = 'Main'`` and ``args = [{"type":"String","value":"test"},[{"type":"Array","value":[{"type":"Integer","value":"10"}]}]]``, but I'm not sure if this is the correct invocation.

Since I am invoking the entry point, shouldn't the result be ``[{"type":"Array","value":[{"type":"Integer","value":"10"}]}]``?

**Comment by Ashuaidehao** [comment]
We don't support to call entry point directly, so the result is correct.
Since neo developers also plans to remove entry point in preview3, the "Main" function will be equally treated as other functions.
